"""Migracion inicial

Revision ID: 64841e34a7cc
Revises: eaa46a4f57eb
Create Date: 2024-10-14 11:05:39.831680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64841e34a7cc'
down_revision = 'eaa46a4f57eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('establecimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('ubicacion', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('establecimiento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimientos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagramas_mensuales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_ini', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empleados',
    sa.Column('legajo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.Column('apellido', sa.String(length=40), nullable=False),
    sa.Column('rol', sa.String(length=40), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('legajo')
    )
    op.create_table('actividades_extraordinarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_ini', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('legajo_empleado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['legajo_empleado'], ['empleados.legajo'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cupos_mensuales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_ini', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('total', sa.Double(), nullable=False),
    sa.Column('remanente', sa.Double(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('legajo_autorizante', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['legajo_autorizante'], ['empleados.legajo'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('legajo_empleado', sa.String(length=20), nullable=False),
    sa.Column('legajo_autorizante', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['legajo_autorizante'], ['empleados.legajo'], ),
    sa.ForeignKeyConstraint(['legajo_empleado'], ['empleados.legajo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actividad_diagrama',
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('diagrama_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades_extraordinarias.id'], ),
    sa.ForeignKeyConstraint(['diagrama_id'], ['diagramas_mensuales.id'], ),
    sa.PrimaryKeyConstraint('actividad_id', 'diagrama_id')
    )
    op.create_table('guardias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duracion', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('cupo_mensual_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cupo_mensual_id'], ['cupos_mensuales.id'], ),
    sa.ForeignKeyConstraint(['id'], ['actividades_extraordinarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traslados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origen', sa.String(length=40), nullable=False),
    sa.Column('destino', sa.String(length=40), nullable=False),
    sa.Column('tramo', sa.Enum('1', '2', '3', name='tramos_enum'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['actividades_extraordinarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traslados')
    op.drop_table('guardias')
    op.drop_table('actividad_diagrama')
    op.drop_table('licencias')
    op.drop_table('cupos_mensuales')
    op.drop_table('actividades_extraordinarias')
    op.drop_table('empleados')
    op.drop_table('diagramas_mensuales')
    op.drop_table('servicios')
    op.drop_table('establecimientos')
    # ### end Alembic commands ###
