"""Se agregan las tablas actividad extraordinaria, guardia y traslado

Revision ID: eaa46a4f57eb
Revises: ffdddb4811dc
Create Date: 2024-09-23 04:30:22.460149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa46a4f57eb'
down_revision = 'ffdddb4811dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades_extraordinarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_ini', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('legajo_empleado', sa.String(length=20), nullable=False),
    sa.Column('diagrama_mensual_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diagrama_mensual_id'], ['diagramas_mensuales.id'], ),
    sa.ForeignKeyConstraint(['legajo_empleado'], ['empleados.legajo'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guardias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duracion', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('cupo_mensual_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cupo_mensual_id'], ['cupos_mensuales.id'], ),
    sa.ForeignKeyConstraint(['id'], ['actividades_extraordinarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traslados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origen', sa.String(length=40), nullable=False),
    sa.Column('destino', sa.String(length=40), nullable=False),
    sa.Column('tramo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['actividades_extraordinarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traslados')
    op.drop_table('guardias')
    op.drop_table('actividades_extraordinarias')
    # ### end Alembic commands ###
